---
create_user: paradmin
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'ufw', 'atop', 'nfs-kernel-server','samba','fuse','mergerfs','gcc','make','zfsutils-linux']